language: ruby
rvm:
- 2.4.0
env:
  matrix:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec
before_install:
  - export TZ=US/Mountain
deploy:
  provider: heroku
  api_key:
    secure: mCJTcQp//m3838TpZZcvpxHkdWhUAvt6DNWSjP4egbtxkUegbJ+g/w2jXqa7PCHRMecDNvBtInqzB5dIzdWHU1dw/WB45ZrLe1e93hRDzk/EWrH83kYIv2fsrPV+ks6LBboKll6FYJpp2nu0SWhN0OQqFlvp5Yksq7XKKI64yC52P8FsOu/l3pxJz67lA+Y5GlHui/Rp9+bji/RldenRNResebYF2szOIMrHZSjXrqjRzkCWVSAZ1cfMUkO68GO5B/UwH4nYE+EYmKvq9jKrOhSyIvLd83FpEySx0ok0hgVAXur+s2MB65H1LBuPeD3tTuTACmf/JxckU+1uN0+ICogi/7wnYuQO8Ktoaw1fA2b+E26LT/fjAUn4oOhXRmXxxNOz5J4zrGMPuco15XYMUicNc/u8EHVJD4i5voNVTzP/onSu5LPQ5YholFQ5EIEEBG1rqLf7NNSiXPdCEzRnojlmU1CSTnuzo4qkGBo/ZP8BKB69bSGFvnLK4uSX0BYTOaIgKYvkRbbM9xr9030SBFkxf6ET9A1M4yWqxbUtAfgSzCTL9rogKiRt5TxrQGngz72IrVusnbLkmEcVta2DffPCG4bIbesFhdYd/HQPR6KOpmcsADmgFFqBKjpmIswWOM47/GXi9kBW8yTLwNIsGgZAYfLYDiVCzDujyugnVxs=
  app: big-blind
  run: rake db:migrate
  on:
    repo: notmarkmiranda/version_10
